repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        files: "^scripts|^tcc/scraper|^tcc/api|^tcc/tests"
  - repo: https://github.com/python-poetry/poetry

    rev: 1.8.3
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
      - id: poetry-install
